<?php

namespace ServiceApresVenteBundle\Repository;

use EmployeBundle\Entity\Employe;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Serializer\Normalizer\ObjectNormalizer;
use Symfony\Component\Serializer\Serializer;

/**
 * FeedbackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeedbackRepository extends \Doctrine\ORM\EntityRepository
{
    public  function calculerTotalFeedback(){

        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('count(f.description)');
        $qb->from('ServiceApresVenteBundle:Feedback','f');

        $count = $qb->getQuery()->getSingleScalarResult();
        return $count;


    }

    public function findEntitiesByString($str){
        return $this->getEntityManager()
            ->createQuery(
                'SELECT a
                FROM ServiceApresVenteBundle:Feedback f
                WHERE f.datefeedback LIKE :str'
            )
            ->setParameter('str', '%'.$str.'%')
            ->getResult();
    }

    public function findOneById()
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('u.mission,u.email,u.username,u.idEmp,u.image');
        $qb->from('EmployeBundle:Employe','u')
            ->andWhere('u.mission IN (:mission)')
            ->setParameter('mission', 'Livreur');
        $liv = $qb->getQuery()->getScalarResult();
        return $liv;
    }





    public function findOneByMission()
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('u.idEmp,u.mission,u.username,u.email,u.image');
        $qb->from('EmployeBundle:Employe','u')
            ->andWhere('u.mission IN (:mission)')
            ->setParameter('mission', 'livreur');
        $liv = $qb->getQuery()->getScalarResult();
        return $liv;
    }




    public function getNbrRating(){

        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('count(f.note)');
        $qb->from('ServiceApresVenteBundle:Rating','f');

        $count = $qb->getQuery()->getSingleScalarResult();
        return $count;


    }


    public function getTotalRateLivreur($id){

        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('count(f.note)');
        $qb->from('ServiceApresVenteBundle:Feedback','f');
        $qb->where('f.livreur=?1');
        $qb->setParameter(1,$id);
        return $qb->getQuery()->getSingleScalarResult();


    }

    public function findNoteByIdLivreur($id)
    {
        $query = $this
            ->getEntityManager()
            ->createQuery("SELECT u.note FROM ServiceApresVenteBundle:Feedback u 
            WHERE u.livreur = ?1")
            ->setParameter(1, $id);
        return $query->getResult();
    }













//    public function getFeedbackByUser($id_feedback){
//        return $this->getEntityManager()
//            ->createQuery(
//                "SELECT f, u.username
//       FROM ServicesApresVenteBundle:Feedback
//       JOIN c.user u
//       WHERE c.feedback = :id"
//            )
//            ->setParameter('id', $id_feedback)
//            ->getArrayResult();
//    }

//    public function getFeedbackById() {
//        $query = $this->getEntityManager()
//            ->createQuery(
//            'SELECT p
//       FROM ServicesApresVenteBundle:Feedback  f'
//
//        );
//
//        $products = $query->getResult();
//        return $query;
//    }

}
