<?php

namespace ServiceApresVenteBundle\Repository;

use ServiceApresVenteBundle\Entity\RecFeedCat;
use ServiceApresVenteBundle\Entity\Reclamation;

/**
 * RecFeedCategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecFeedCategorieRepository extends \Doctrine\ORM\EntityRepository
{

}