# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
# app/config/security.yml
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_ADMIN
#        ROLE_SUPER_ADMIN: ROLE_ADMIN
        ROLE_CLIENT:      ROLE_CLIENT
#        Societe:
        ROLE_SOCIETE: ROLE_SOCIETE
        ROLE_CLIENT: ROLE_CLIENT

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        main:
            pattern: ^/
            user_checker: security.user_checker
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                always_use_default_target_path: false
                default_target_path: /home

            logout:
                path: fos_user_security_logout
                target: /Accueil
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }

      
