<?php

namespace EmployeeBundle\Repository;

/**
 * employeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class employeeRepository extends \Doctrine\ORM\EntityRepository
{
}
